### PR TITLE
Add Netlify Gatsby cache plugin

### PR DESCRIPTION
**Pull request by ehmicky**
This adds Netlify Gatsby cache plugin.

This plugin was previously added but removed due to a bug reported [here](https://github.com/netlify/build/issues/1069).

I could not reproduce the problem, so I think this might have been fixed in the latest Netlify Build since we fixed several caching-related issues. 

I am going to try to push to this PR several times in a row to ensure that the problem you encountered is not there anymore. Please keep this PR open until I can confirm everything looks good, thanks!

### CODE REVIEW

**Comment by RNR1** [comment]
i think that's the problem i am experiencing either, thanks!

**Comment by ehmicky** [comment]
@RNR1 Could you please describe your problem? I am looking for any additional debugging information.

If possible, please do so on https://github.com/netlify/build/issues/1069 (if that's the exact same problem) or by posting a new issue on https://github.com/netlify/build/issues (otherwise). Thanks!

**Comment by RNR1** [comment]
well after checking for further info in the issue, i'm not sure that's it, my problem is on getting the images from cache when running npm run develop. then it's not showing the category photos on main page.

**Comment by jasonLaster** [comment]
@ehmicky do we want to also restrict the CDN publish to the `public` directory?

**Comment by ehmicky** [comment]
It turns out only the `public` directory is published to the CDN, so all is good there :+1: 

I have investigated more this issue and summarized my findings [in this comment](https://github.com/netlify/build/issues/1069#issuecomment-607262367). In a nutshell I would recommend:
  - First fixing #199 and #81
  - Then merging this PR
  - If the problem is still occurring, re-opening https://github.com/netlify/build/issues/1069

**Comment by jasonLaster** [comment]
Thanks @ehmicky

**Comment by bahmutov** [comment]
@ehmicky you are fixing Netlify plugins here and NOT suggesting using Cypress for testing either on Netlify or on GitHub, I am disappointed

**Comment by jasonLaster** [comment]
@bahmutov i wouldn't be surprised if every climate site were using cypress in the next couple of months 😉

**Pull request merged**
