### PR TITLE
This adds support for eslint

### PR DESCRIPTION
**Pull request by jasonLaster**
It is somewhat scary to see all of the changes, but 99% is autogenerated

- I changed the component keys to use something other than indices
- I escaped characters like '

We should land something when it works and then iterate on the configuration. For instance, if we want to go from 80 chars to 100 we can file an issue for that.

### CODE REVIEW

**Comment by bloudermilk** [comment]
@jasonLaster more or less happy with all the enforced rules and definitely happy to have some consistency. Couple of questions for you:

* Can you explain the "Why" of the two decisions you noted in the PR description?
* How should we integrate this into our development process?

**Comment by jasonLaster** [comment]
Both of those decisions were enforced by eslint rules.

The react keys thing makes sense because react should know which component was added, removed, changed. https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md

the encoding thing i assume is to disambiguate... not really sure

**Comment by jasonLaster** [comment]
I'll file a ticket for this, but i hope to have circle ci validating eslint rules shortly

**Comment by bloudermilk** [comment]
@jasonLaster I'm not fully caught up on the latest features here, but I wonder if Netlify or GitHub could run this w/o needing to add another service? I suspect either or both could.

**Pull request merged**
