### PR TITLE
Introduce organisation meta data

### PR DESCRIPTION
**Pull request by jamescrowley**
Initial attempt addressing https://github.com/climatescape/climatescape.org/issues/32

* logo - added in greyscale (personal preference vs a list full of clashing colourful logos)
* tagline - preferring the description from LinkedIn
* location - just went comma delimited, removing duplicate/whitespace
* headcount - used an icon
* company type

Screenshot 2020-01-22 at 14 30 46

### CODE REVIEW

**Comment by jamescrowley** [comment]
@bloudermilk I wasn't quite sure about bringing in a react component just to embed icons, but I couldn't find a 'simple' way to do it otherwise - feel free to make other suggestions!

**Comment by jamescrowley** [comment]
Updated with an icon for tags, and a bit more spacing

Screenshot 2020-01-22 at 14 41 25

**Comment by jamescrowley** [comment]
Added support for filtering on these new attributes - hopefully in a way that lets us easily improve the filtering in the future.

Screenshot 2020-01-22 at 19 25 54

**Comment by bloudermilk** [comment]
@jamescrowley this was a huge improvement to the site. Thank you so much for your contribution!

**Pull request merged**
