### PR TITLE
Add cypress support

### PR DESCRIPTION
**Pull request by jasonLaster**
Adds a small cypress test that verifies that we can visit the homepage, orgs list, and org page.

### CODE REVIEW

**Comment by jasonLaster** [comment]
Huge thanks to @bahmutov for the help setting up the first test

**Comment by bloudermilk** [comment]
@jasonLaster is this close to being ready?

**Comment by jasonLaster** [comment]
Yes, we just need to figure out how to do the build in the action

**Comment by bloudermilk** [comment]
Closing this as stale.

**Pull request closed without merging**
